name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: 🛠️ Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: 📦 Install Dependencies
        run: bun install

      - name: 🏗️ Build
        run: bun build src/index.js --target=bun --format=esm --minify --outfile=bin/index.js --external=typescript
      
      - name: 🚀 Publish
        run: npm publish